version: '3.9'
services:
  neo4j:
    image: neo4j:latest
    ports: 
      # Port for neo4j web DB inspection tool
      - 7474:7474
      # Actual database port
      - 7687:7687
    volumes:
      - neo4j_db:/data/
      - neo4j_plugins:/plugins/
    env_file:
      - .env
    environment:
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_uuid_enabled=true
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
      interval: 7s
      timeout: 5s
      retries: 3
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    # FIXME Provide .env file
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend
  data-processor:
    container_name: data-processor
    build:
      context: ./packages/dataProcessor
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_started
      neo4j:
        condition: service_healthy
    networks:
      - backend
    env_file:
      - .env
    volumes:
      - ./packages/dataProcessor:/usr/src/dataProcessor
    stop_signal: SIGINT
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 3072M
        reservations:
          cpus: '0.5'
          memory: 1024M

networks:
  backend:
    driver: bridge
volumes:
  neo4j_db:
    driver: local
    name: neo4j_db
  neo4j_plugins:
    driver: local
    name: neo4j_plugins
  rabbitmq_data:
    driver: local
    name: rabbitmq_data
